CREATE TABLE PULL_REQUESTS
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   NUMBER int,
   AUTHOR varchar(255),
   BASE_BRANCH varchar(255),
   HEAD_BRANCH varchar(255),
   REPO_URL varchar(1000),
   IS_OPEN int
);
CREATE TABLE REPORTED_UPDATES
(
   PULL_REQUEST_ID varchar(255) NOT NULL,
   COMMIT_ID varchar(1000) NOT NULL,
   IS_REPORTED int,
   CONSTRAINT PK_REPORTED_UPDATES PRIMARY KEY (PULL_REQUEST_ID,COMMIT_ID)
);